(function(){
  var P = window.ASSET_PREFIX || '';
  window.BOOKS = [
    {slug:'the-code-we-write-in-fire',title:'The Code We Write in Fire',sub:'Book One',pen:'Vesper Locke',world:'vesper',genre:'Science Fiction',status:'live',rot:1,hook:'A literary science fiction thriller about a city, a hidden message, and the price of perfect peace.',cover:{img:'the-code-we-write-in-fire.png'},link:'books/the-code-we-write-in-fire/index.html',sample:'books/the-code-we-write-in-fire/index.html#sample',buy:'https://shop.boompublishingbooks.com/products/the-code-we-write-in-fire'},
    {slug:'when-i-see-through-you',title:'When I See Through You',sub:'A novel',pen:'Mira Lavelle',world:'mira',genre:'Historical Romance',status:'live',rot:2,hook:'A sweeping historical romance about memory, distance, and the long road back to love.',cover:{img:'when-i-see-through-you.png'},link:'books/when-i-see-through-you/index.html',sample:'books/when-i-see-through-you/index.html'},
    {slug:'the-bridge-walker',title:'The Accidental Nexus',sub:'The Bridge-Walker · Book One',pen:'Eveline Cross',world:'eveline',genre:'Portal Fantasy',status:'live',rot:3,hook:'A portal fantasy about impossible doors, courage, and the cost of crossing between worlds.',cover:{img:'accidental-nexus.png'},link:'books/the-accidental-nexus/index.html',sample:'books/the-accidental-nexus/index.html'},
    {slug:'the-opponent',title:'The Opponent',sub:'Book One',pen:'Vesper Locke',world:'vesper',genre:'Science Fiction',status:'soon',release:'Dec 2026',stage:'First draft',hook:'A future athlete discovers the truth behind the Games and must choose what kind of champion to become.',cover:{img:'the-opponent.png'},link:'books/the-opponent/index.html'},
    {slug:'the-mirage-queen',title:'The Mirage Queen',sub:'The Bridge-Walker · Book Two',pen:'Eveline Cross',world:'eveline',genre:'Portal Fantasy',status:'soon',release:'Sept 2026',stage:'First draft',hook:'The next Bridge-Walker story.',cover:{img:'the-mirage-queen.png'},link:'books/the-mirage-queen/index.html'},
    {slug:'this-version-of-us',title:'This Version of Us',sub:'A novel',pen:'Mira Lavelle',world:'mira',genre:'Contemporary Romance',status:'soon',release:'Sept 2026',stage:'Revised draft',feature:true,rot:4,hook:'A contemporary romance about being known, being loved, and learning the difference.',cover:{img:'this-version-of-us.png'},link:'books/this-version-of-us/index.html'}
  ];
  window.WORLDS={vesper:{name:'Vesper Locke',genre:'Science Fiction & Space Opera',page:'worlds/vesper-locke.html'},eveline:{name:'Eveline Cross',genre:'Portal Fantasy & Adventure',page:'worlds/eveline-cross.html'},mira:{name:'Mira Lavelle',genre:'Romance & Gothic Suspense',page:'worlds/mira-lavelle.html'}};
  function esc(s){return(s+'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
  function href(u){return /^https?:\/\//.test(u||'')?u:P+u}
  window.coverHTML=function(b){return '<img src="'+P+'covers/'+b.cover.img+'" alt="'+esc(b.title)+' cover" loading="lazy">'};
  var STATUS={live:'Available',soon:'Coming soon',vote:'Help me choose'};
  function style(){if(document.getElementById('book-action-styles'))return;var s=document.createElement('style');s.id='book-action-styles';s.textContent='.tile{display:flex;flex-direction:column}.tile>a{color:inherit;text-decoration:none}.book-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.book-btn{display:inline-flex;align-items:center;justify-content:center;min-height:34px;padding:8px 11px;border:1px solid rgba(217,180,106,.45);border-radius:999px;color:#f2dfad;text-decoration:none;font:700 11px/1 Arial,Helvetica,sans-serif;letter-spacing:.06em;text-transform:uppercase;background:rgba(0,0,0,.14)}.book-btn-primary{background:#d9b46a;color:#160f09;border-color:#d9b46a}';document.head.appendChild(s)}
  function actions(b){if(b.status!=='live')return'';var h='<div class="book-actions">';if(b.buy)h+='<a class="book-btn book-btn-primary" href="'+href(b.buy)+'">Buy from Publisher</a>';h+='<a class="book-btn" href="'+href(b.sample||b.link)+'">Read Sample</a></div>';return h}
  window.tileHTML=function(b){style();return '<div class="tile" data-world="'+b.world+'" data-status="'+b.status+'"><a href="'+P+b.link+'"><div class="tilecover"><span class="badge '+b.status+'">'+STATUS[b.status]+(b.release?' · '+esc(b.release):'')+'</span>'+window.coverHTML(b)+'</div><div class="tilecap"><div class="t">'+esc(b.title)+'</div><div class="p">'+esc(b.pen)+' · '+esc(b.genre)+'</div>'+(b.stage?'<div class="p" style="font-size:11px;opacity:.65;margin-top:3px">'+esc(b.stage)+'</div>':'')+'</div></a>'+actions(b)+'</div>'};
  window.renderShelf=function(sel,opts){opts=opts||{};var host=document.querySelector(sel);if(!host)return;var list=window.BOOKS.filter(opts.filter||function(){return true});var chipsHTML='';if(opts.chips){var sets=[['all','All'],['vesper','Sci-Fi'],['eveline','Fantasy'],['mira','Romance'],['live','Available'],['soon','Coming soon']];chipsHTML='<div class="chips">'+sets.map(function(s,i){return '<button class="chip'+(i===0?' on':'')+'" data-f="'+s[0]+'">'+s[1]+'</button>'}).join('')+'</div>'}host.innerHTML=chipsHTML+'<div class="shelf">'+list.map(window.tileHTML).join('')+'</div>';if(opts.chips){host.querySelectorAll('.chip').forEach(function(ch){ch.addEventListener('click',function(){host.querySelectorAll('.chip').forEach(function(c){c.classList.remove('on')});ch.classList.add('on');var f=ch.dataset.f;host.querySelectorAll('.tile').forEach(function(t){var show=f==='all'||t.dataset.world===f||t.dataset.status===f;t.style.display=show?'':'none'})})})}};
  window.initRotation=function(sel,opts){opts=opts||{};var host=document.querySelector(sel);if(!host)return;var list=window.BOOKS.filter(function(b){return b.status==='live'||b.feature});list.sort(function(a,b){return(a.rot||99)-(b.rot||99)});var slides=list.map(function(b){return '<div class="slide" data-world="'+b.world+'"><a class="rcover" href="'+P+b.link+'">'+window.coverHTML(b)+'</a><div class="rmeta"><p class="reyebrow">'+esc(b.genre)+'</p>'+(b.status!=='live'?'<p style="display:inline-block;margin:2px 0 8px;padding:5px 13px;border:1px solid #d9b46a;border-radius:999px;color:#d9b46a;font-family:Arial,Helvetica,sans-serif;font-size:11.5px;letter-spacing:.1em;text-transform:uppercase">Coming soon'+(b.release?' &#183; '+esc(b.release):'')+'</p>':'')+'<h1 class="rtitle">'+esc(b.title)+'</h1><div class="rsub">'+esc(b.sub)+'</div><p class="rhook">'+esc(b.hook)+'</p><p class="rpen">a novel by '+esc(b.pen)+'</p><div class="rcta"><a class="btn primary" href="'+P+b.link+'">Enter this book</a>'+(b.buy?'<a class="btn ghost" href="'+href(b.buy)+'">Buy from Publisher</a>':'')+'</div></div></div>'}).join('');host.innerHTML='<div class="hero"><div class="stars"></div><div class="rstage" id="rstage">'+slides+'</div></div><div class="rctrls"><button class="rarrow" id="rprev" aria-label="Previous">‹</button><div class="rdots" id="rdots"></div><button class="rarrow" id="rnext" aria-label="Next">›</button></div>';var stage=host.querySelector('#rstage'),dotsHost=host.querySelector('#rdots'),els=stage.querySelectorAll('.slide'),i=0,timer=null,reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion:reduce)').matches;dotsHost.innerHTML=list.map(function(_,k){return '<button class="rdot" data-k="'+k+'"></button>'}).join('');var dots=dotsHost.querySelectorAll('.rdot');function show(n){i=(n+els.length)%els.length;els.forEach(function(e,k){e.classList.toggle('on',k===i)});dots.forEach(function(d,k){d.classList.toggle('on',k===i)});host.querySelector('.hero').className='hero world-'+els[i].getAttribute('data-world')}function next(){show(i+1)}function prev(){show(i-1)}function play(){if(reduce)return;stop();timer=setInterval(next,opts.interval||6000)}function stop(){if(timer){clearInterval(timer);timer=null}}host.querySelector('#rnext').addEventListener('click',function(){next();play()});host.querySelector('#rprev').addEventListener('click',function(){prev();play()});dots.forEach(function(d){d.addEventListener('click',function(){show(+d.dataset.k);play()})});host.addEventListener('mouseenter',stop);host.addEventListener('mouseleave',play);show(0);play()};
})();